"""decompose author birth/death dates

Revision ID: 04e051f36fca
Revises: e91ff566a273
Create Date: 2025-08-24 12:40:12.593161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e051f36fca'
down_revision: Union[str, None] = 'e91ff566a273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_author', sa.Column('birthday_year', sa.SmallInteger(), nullable=True))
    op.add_column('book_author', sa.Column('birthday_month', sa.SmallInteger(), nullable=True))
    op.add_column('book_author', sa.Column('birthday_day', sa.SmallInteger(), nullable=True))
    op.add_column('book_author', sa.Column('death_date_year', sa.SmallInteger(), nullable=True))
    op.add_column('book_author', sa.Column('death_date_month', sa.SmallInteger(), nullable=True))
    op.add_column('book_author', sa.Column('death_date_day', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_author', 'death_date_day')
    op.drop_column('book_author', 'death_date_month')
    op.drop_column('book_author', 'death_date_year')
    op.drop_column('book_author', 'birthday_day')
    op.drop_column('book_author', 'birthday_month')
    op.drop_column('book_author', 'birthday_year')
    # ### end Alembic commands ###
