"""change library table structure

Revision ID: 0c4f71795dea
Revises: 453ff4bdecd4
Create Date: 2024-09-08 00:36:41.460172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c4f71795dea'
down_revision: Union[str, None] = '453ff4bdecd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('author_additional_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('library', sa.Column('composition_language_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('language1_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('language2_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('language3_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('translator_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('translator_additional_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('library', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.alter_column('library', 'binding',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_index('ix_library_binding', table_name='library')
    op.drop_index('ix_library_language1', table_name='library')
    op.drop_index('ix_library_language_composition', table_name='library')
    op.create_index(op.f('ix_library_author_id'), 'library', ['author_id'], unique=False)
    op.create_index(op.f('ix_library_composition_language_id'), 'library', ['composition_language_id'], unique=False)
    op.create_index(op.f('ix_library_language1_id'), 'library', ['language1_id'], unique=False)
    op.create_foreign_key('library_language3_id_fkey', 'library', 'language', ['language3_id'], ['id'])
    op.create_foreign_key('library_binding_fkey', 'library', 'binding', ['binding'], ['id'])
    op.create_foreign_key('library_translator_id_fkey', 'library', 'author', ['translator_id'], ['id'])
    op.create_foreign_key('library_author_id_fkey', 'library', 'author', ['author_id'], ['id'])
    op.create_foreign_key('library_language2_id_fkey', 'library', 'language', ['language2_id'], ['id'])
    op.create_foreign_key('library_publisher_id_fkey', 'library', 'publisher', ['publisher_id'], ['id'])
    op.create_foreign_key('library_composition_language_id_fkey', 'library', 'language', ['composition_language_id'], ['id'])
    op.create_foreign_key('library_language1_id_fkey', 'library', 'language', ['language1_id'], ['id'])
    op.drop_column('library', 'author')
    op.drop_column('library', 'author_last_name')
    op.drop_column('library', 'author_first_name')
    op.drop_column('library', 'language2')
    op.drop_column('library', 'language3')
    op.drop_column('library', 'language1')
    op.drop_column('library', 'publisher')
    op.drop_column('library', 'translator_additional')
    op.drop_column('library', 'translator')
    op.drop_column('library', 'language_composition')
    op.drop_column('library', 'author_additional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('author_additional', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('language_composition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('translator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('translator_additional', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('language1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('language3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('language2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('author_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('author_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('library_language1_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_language2_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_language3_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_author_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_binding_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_composition_language_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_publisher_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_translator_id_fkey', 'library', type_='foreignkey')
    op.drop_index(op.f('ix_library_language1_id'), table_name='library')
    op.drop_index(op.f('ix_library_composition_language_id'), table_name='library')
    op.drop_index(op.f('ix_library_author_id'), table_name='library')
    op.create_index('ix_library_language_composition', 'library', ['language_composition'], unique=False)
    op.create_index('ix_library_language1', 'library', ['language1'], unique=False)
    op.create_index('ix_library_binding', 'library', ['binding'], unique=False)
    op.alter_column('library', 'binding',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('library', 'publisher_id')
    op.drop_column('library', 'translator_additional_id')
    op.drop_column('library', 'translator_id')
    op.drop_column('library', 'language3_id')
    op.drop_column('library', 'language2_id')
    op.drop_column('library', 'language1_id')
    op.drop_column('library', 'composition_language_id')
    op.drop_column('library', 'author_additional_id')
    op.drop_column('library', 'author_id')
    # ### end Alembic commands ###
