"""expense_budget

Revision ID: 195b19ae6c49
Revises: d72fd54b6da7
Create Date: 2025-02-01 20:51:09.687912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '195b19ae6c49'
down_revision: Union[str, None] = 'd72fd54b6da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_budget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_start_date', sa.Date(), nullable=True),
    sa.Column('budget_end_date', sa.Date(), nullable=True),
    sa.Column('income_expense', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_budget_budget_end_date'), 'expense_budget', ['budget_end_date'], unique=False)
    op.create_index(op.f('ix_expense_budget_budget_start_date'), 'expense_budget', ['budget_start_date'], unique=False)
    op.add_column('expense_transactions', sa.Column('expense_budget_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'expense_budget_id')
    op.drop_index(op.f('ix_expense_budget_budget_start_date'), table_name='expense_budget')
    op.drop_index(op.f('ix_expense_budget_budget_end_date'), table_name='expense_budget')
    op.drop_table('expense_budget')
    # ### end Alembic commands ###
