"""change cartridge_id to ammunition_id

Revision ID: 1b19233e7d43
Revises: 9e72b9aad179
Create Date: 2024-12-14 18:02:32.025080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b19233e7d43'
down_revision: Union[str, None] = '9e72b9aad179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('firearm_ammunition_id', sa.Integer(), nullable=True))
    op.drop_constraint('firearm_end_firearm_cartridge_id_fkey', 'firearm_end', type_='foreignkey')
    op.create_foreign_key(None, 'firearm_end', 'firearm_ammunition', ['firearm_ammunition_id'], ['id'])
    op.drop_column('firearm_end', 'firearm_cartridge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('firearm_cartridge_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'firearm_end', type_='foreignkey')
    op.create_foreign_key('firearm_end_firearm_cartridge_id_fkey', 'firearm_end', 'firearm_cartridge', ['firearm_cartridge_id'], ['id'])
    op.drop_column('firearm_end', 'firearm_ammunition_id')
    # ### end Alembic commands ###
