"""add temporal columns

Revision ID: 278ca4453b3c
Revises: f7dfa3d8f3e4
Create Date: 2024-12-14 17:43:34.388896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '278ca4453b3c'
down_revision: Union[str, None] = 'f7dfa3d8f3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_model', sa.Column('datetime_valid_start', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('firearm_model', sa.Column('datetime_valid_end', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('firearm_restriction', sa.Column('datetime_valid_start', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('firearm_restriction', sa.Column('datetime_valid_end', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_restriction', 'datetime_valid_end')
    op.drop_column('firearm_restriction', 'datetime_valid_start')
    op.drop_column('firearm_model', 'datetime_valid_end')
    op.drop_column('firearm_model', 'datetime_valid_start')
    # ### end Alembic commands ###
