"""add firearm_sight

Revision ID: 2e346993059b
Revises: 429a0239974f
Create Date: 2024-11-23 15:43:54.874653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e346993059b'
down_revision: Union[str, None] = '429a0239974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firearm_sight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=90), nullable=True),
    sa.Column('firearm_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_magnification', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['firearm_manufacturer_id'], ['firearm_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('firearm_end', sa.Column('firearm_sight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'firearm_end', 'firearm_sight', ['firearm_sight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'firearm_end', type_='foreignkey')
    op.drop_column('firearm_end', 'firearm_sight_id')
    op.drop_table('firearm_sight')
    # ### end Alembic commands ###
