"""add archery_scoring_rule

Revision ID: 2f6ba5f423d2
Revises: b602776aa9c4
Create Date: 2025-05-22 21:36:50.848876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f6ba5f423d2'
down_revision: Union[str, None] = 'b602776aa9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archery_scoring_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('archery_round', sa.Column('archery_scoring_rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'archery_round', 'archery_scoring_rule', ['archery_scoring_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archery_round', type_='foreignkey')
    op.drop_column('archery_round', 'archery_scoring_rule_id')
    op.drop_table('archery_scoring_rule')
    # ### end Alembic commands ###
