"""add short_name columns

Revision ID: 34f546313bea
Revises: df161e49edd9
Create Date: 2026-08-31 23:05:57.133264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f546313bea'
down_revision: Union[str, None] = 'df161e49edd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_ammunition', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('firearm_manufacturer', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('firearm_model', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_model', 'short_name')
    op.drop_column('firearm_manufacturer', 'short_name')
    op.drop_column('firearm_cartridge', 'short_name')
    op.drop_column('firearm_ammunition', 'short_name')
    # ### end Alembic commands ###
