"""move archery_round.magnification to archery_sight

Revision ID: 35782ed4788a
Revises: 94e0177a98ad
Create Date: 2025-03-22 22:05:15.528815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35782ed4788a'
down_revision: Union[str, None] = '94e0177a98ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archery_round', 'magnification')
    op.add_column('archery_sight', sa.Column('magnification', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archery_sight', 'magnification')
    op.add_column('archery_round', sa.Column('magnification', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
