"""add archery_round.archery_sight_id

Revision ID: 3f8cd53ea2c3
Revises: a26f5d68f9c7
Create Date: 2025-03-08 23:40:14.701356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8cd53ea2c3'
down_revision: Union[str, None] = 'a26f5d68f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('archery_sight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'archery_round', 'archery_sight', ['archery_sight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archery_round', type_='foreignkey')
    op.drop_column('archery_round', 'archery_sight_id')
    # ### end Alembic commands ###
