"""points of stabilisation

Revision ID: 429a0239974f
Revises: d499baa2a116
Create Date: 2024-11-16 16:51:54.580320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429a0239974f'
down_revision: Union[str, None] = 'd499baa2a116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('points_of_stabilisation', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_end', 'points_of_stabilisation')
    # ### end Alembic commands ###
