"""add archery_rounds.avg_shots

Revision ID: 67ab9433f6c7
Revises: 84012a6ddbc5
Create Date: 2024-10-21 21:41:41.400034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ab9433f6c7'
down_revision: Union[str, None] = '84012a6ddbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('avg_shots', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archery_round', 'avg_shots')
    # ### end Alembic commands ###
