"""correct column typo

Revision ID: 688931b9d9c6
Revises: 2ece45329356
Create Date: 2024-10-19 22:42:08.991089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688931b9d9c6'
down_revision: Union[str, None] = '2ece45329356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('stabilisation', sa.Boolean(), nullable=False))
    op.drop_column('archery_round', 'stablisation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('stablisation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('archery_round', 'stabilisation')
    # ### end Alembic commands ###
