"""add book_series.publisher_id

Revision ID: 6894690d7d91
Revises: cb3f76b0dfb9
Create Date: 2025-08-24 11:44:54.619487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6894690d7d91'
down_revision: Union[str, None] = 'cb3f76b0dfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_series', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_series', 'book_publisher', ['publisher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_series', type_='foreignkey')
    op.drop_column('book_series', 'publisher_id')
    # ### end Alembic commands ###
