"""add archery_round.seconds_per_arrow

Revision ID: 69f0e15470dc
Revises: dbe07ac1ae47
Create Date: 2026-01-13 21:07:18.198710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f0e15470dc'
down_revision: Union[str, None] = 'dbe07ac1ae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('seconds_per_arrow', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archery_round', 'seconds_per_arrow')
    # ### end Alembic commands ###
