"""revise firearm_model column names

Revision ID: 6b37f3c623fd
Revises: 688931b9d9c6
Create Date: 2024-10-19 23:15:55.908294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b37f3c623fd'
down_revision: Union[str, None] = '688931b9d9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id1', sa.Integer(), nullable=False))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id2', sa.Integer(), nullable=True))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id3', sa.Integer(), nullable=True))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id4', sa.Integer(), nullable=True))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id5', sa.Integer(), nullable=True))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id6', sa.Integer(), nullable=True))
    op.add_column('firearm_model', sa.Column('firearm_cartridge_id7', sa.Integer(), nullable=True))
    op.drop_constraint('firearm_model_cartridge_id5_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id4_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id1_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id7_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id3_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id6_fkey', 'firearm_model', type_='foreignkey')
    op.drop_constraint('firearm_model_cartridge_id2_fkey', 'firearm_model', type_='foreignkey')
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id4'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id3'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id6'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id7'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id1'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id5'], ['id'])
    op.create_foreign_key(None, 'firearm_model', 'firearm_cartridge', ['firearm_cartridge_id2'], ['id'])
    op.drop_column('firearm_model', 'cartridge_id4')
    op.drop_column('firearm_model', 'cartridge_id6')
    op.drop_column('firearm_model', 'cartridge_id2')
    op.drop_column('firearm_model', 'cartridge_id7')
    op.drop_column('firearm_model', 'cartridge_id1')
    op.drop_column('firearm_model', 'cartridge_id3')
    op.drop_column('firearm_model', 'cartridge_id5')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_model', sa.Column('cartridge_id5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('firearm_model', sa.Column('cartridge_id3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('firearm_model', sa.Column('cartridge_id1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('firearm_model', sa.Column('cartridge_id7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('firearm_model', sa.Column('cartridge_id2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('firearm_model', sa.Column('cartridge_id6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('firearm_model', sa.Column('cartridge_id4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.drop_constraint(None, 'firearm_model', type_='foreignkey')
    op.create_foreign_key('firearm_model_cartridge_id2_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id2'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id6_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id6'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id3_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id3'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id7_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id7'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id1_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id1'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id4_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id4'], ['id'])
    op.create_foreign_key('firearm_model_cartridge_id5_fkey', 'firearm_model', 'firearm_cartridge', ['cartridge_id5'], ['id'])
    op.drop_column('firearm_model', 'firearm_cartridge_id7')
    op.drop_column('firearm_model', 'firearm_cartridge_id6')
    op.drop_column('firearm_model', 'firearm_cartridge_id5')
    op.drop_column('firearm_model', 'firearm_cartridge_id4')
    op.drop_column('firearm_model', 'firearm_cartridge_id3')
    op.drop_column('firearm_model', 'firearm_cartridge_id2')
    op.drop_column('firearm_model', 'firearm_cartridge_id1')
    # ### end Alembic commands ###
