"""add book.edition

Revision ID: 6e8dc356df8b
Revises: 7f1448c0f451
Create Date: 2025-08-23 19:31:35.255566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8dc356df8b'
down_revision: Union[str, None] = '7f1448c0f451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('edition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'edition')
    # ### end Alembic commands ###
