"""add firearm_visit.visit_date

Revision ID: 700110d75a67
Revises: 6b37f3c623fd
Create Date: 2024-10-19 23:17:47.854552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700110d75a67'
down_revision: Union[str, None] = '6b37f3c623fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_visit', sa.Column('visit_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_firearm_visit_visit_date'), 'firearm_visit', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firearm_visit_visit_date'), table_name='firearm_visit')
    op.drop_column('firearm_visit', 'visit_date')
    # ### end Alembic commands ###
