"""add credentials table

Revision ID: 75ce863c48cd
Revises: 8c69f78a003a
Create Date: 2024-02-23 21:41:49.531060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ce863c48cd'
down_revision: Union[str, None] = '8c69f78a003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column(
        'last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True,
        server_onupdate=sa.text('now()')
    ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_credentials_importance'), 'credentials', ['importance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_importance'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
