"""add firearm_ammunition.num_pellets

Revision ID: 7cd2d452f6ca
Revises: a5930e0bfbae
Create Date: 2024-12-14 19:23:33.023228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd2d452f6ca'
down_revision: Union[str, None] = 'a5930e0bfbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_ammunition', sa.Column('num_pellets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_ammunition', 'num_pellets')
    # ### end Alembic commands ###
