"""add firearm_target.target_name

Revision ID: 7d290d282b91
Revises: 195b19ae6c49
Create Date: 2025-02-09 23:08:27.050761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d290d282b91'
down_revision: Union[str, None] = '195b19ae6c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_target', sa.Column('target_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_target', 'target_name')
    # ### end Alembic commands ###
