"""add book_editor

Revision ID: 7f1448c0f451
Revises: aacf8ea7e41c
Create Date: 2025-08-23 19:07:12.348015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1448c0f451'
down_revision: Union[str, None] = 'aacf8ea7e41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_editor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_to_book_editor',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_editor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_editor_id'], ['book_editor.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'book_editor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_to_book_editor')
    op.drop_table('book_editor')
    # ### end Alembic commands ###
