"""relax firearm_end column nullable constraints

Revision ID: 84012a6ddbc5
Revises: 700110d75a67
Create Date: 2024-10-19 23:20:36.150194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84012a6ddbc5'
down_revision: Union[str, None] = '700110d75a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firearm_end', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('firearm_end', 'distance_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firearm_end', 'distance_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('firearm_end', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
