"""add remark columns to firearm tables

Revision ID: 890f36767f46
Revises: cf05efc480eb
Create Date: 2026-08-31 20:32:20.320744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890f36767f46'
down_revision: Union[str, None] = 'cf05efc480eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('double_trap_round', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('firearm_end', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('skeet_round', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('trap_round', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trap_round', 'remarks')
    op.drop_column('skeet_round', 'remarks')
    op.drop_column('firearm_end', 'remarks')
    op.drop_column('double_trap_round', 'remarks')
    # ### end Alembic commands ###
