"""add missing columns in rounds

Revision ID: 8c69f78a003a
Revises: be4279d86e51
Create Date: 2023-11-10 22:54:02.935314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c69f78a003a'
down_revision: Union[str, None] = 'be4279d86e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('distance_m', sa.Integer(), nullable=False))
    op.add_column('rounds', sa.Column('target_size_cm', sa.Integer(), nullable=False))
    op.add_column('rounds', sa.Column('sight', sa.Boolean(), nullable=False))
    op.add_column('rounds', sa.Column('clicker', sa.Boolean(), nullable=False))
    op.add_column('rounds', sa.Column('stabliser', sa.Boolean(), nullable=False))
    op.add_column('rounds', sa.Column('bow', sa.String(), nullable=False))
    op.add_column('rounds', sa.Column('arrow_stiffness', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rounds_bow'), 'rounds', ['bow'], unique=False)
    op.create_index(op.f('ix_rounds_distance_m'), 'rounds', ['distance_m'], unique=False)
    op.create_index(op.f('ix_rounds_round_date'), 'rounds', ['round_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_round_date'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_distance_m'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_bow'), table_name='rounds')
    op.drop_column('rounds', 'arrow_stiffness')
    op.drop_column('rounds', 'bow')
    op.drop_column('rounds', 'stabliser')
    op.drop_column('rounds', 'clicker')
    op.drop_column('rounds', 'sight')
    op.drop_column('rounds', 'target_size_cm')
    op.drop_column('rounds', 'distance_m')
    # ### end Alembic commands ###
