"""upgrade to head

Revision ID: 9077020939f5
Revises: 
Create Date: 2024-06-16 17:06:09.541026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9077020939f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_credentials_importance'), 'credentials', ['importance'], unique=False)
    op.create_table('expense_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('expense_source', sa.String(), nullable=True),
    sa.Column('expense_comment', sa.String(), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_transactions_transaction_date'), 'expense_transactions', ['transaction_date'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_date', sa.Date(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('target_size_cm', sa.Integer(), nullable=False),
    sa.Column('sight', sa.Boolean(), nullable=False),
    sa.Column('clicker', sa.Boolean(), nullable=False),
    sa.Column('stabliser', sa.Boolean(), nullable=False),
    sa.Column('bow', sa.String(), nullable=False),
    sa.Column('arrow_stiffness', sa.Integer(), nullable=True),
    sa.Column('bow_weight_lb', sa.Integer(), nullable=False),
    sa.Column('bow_length_in', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('num_x', sa.Integer(), nullable=False),
    sa.Column('num_10', sa.Integer(), nullable=False),
    sa.Column('num_9', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('mental_status', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Boolean(), nullable=True),
    sa.Column('days_since_last_practice', sa.Integer(), nullable=True),
    sa.Column('stdev_ends', sa.Float(), nullable=False),
    sa.Column('stdev_shots', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_bow'), 'rounds', ['bow'], unique=False)
    op.create_index(op.f('ix_rounds_bow_weight_lb'), 'rounds', ['bow_weight_lb'], unique=False)
    op.create_index(op.f('ix_rounds_distance_m'), 'rounds', ['distance_m'], unique=False)
    op.create_index(op.f('ix_rounds_location'), 'rounds', ['location'], unique=False)
    op.create_index(op.f('ix_rounds_round_date'), 'rounds', ['round_date'], unique=False)
    op.create_index(op.f('ix_rounds_total_score'), 'rounds', ['total_score'], unique=False)
    op.create_table('ends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rounds_id', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('shots_ordered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rounds_id'], ['rounds.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ends_rounds_id'), 'ends', ['rounds_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ends_id', sa.Integer(), nullable=False),
    sa.Column('shot', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_x', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ends_id'], ['ends.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_index(op.f('ix_ends_rounds_id'), table_name='ends')
    op.drop_table('ends')
    op.drop_index(op.f('ix_rounds_total_score'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_round_date'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_location'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_distance_m'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_bow_weight_lb'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_bow'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_expense_transactions_transaction_date'), table_name='expense_transactions')
    op.drop_table('expense_transactions')
    op.drop_index(op.f('ix_credentials_importance'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
