"""add shot load columns in firearm_cartridge

Revision ID: 9337aac80759
Revises: 98f4649a2473
Create Date: 2025-11-23 20:43:40.362536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9337aac80759'
down_revision: Union[str, None] = '98f4649a2473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('shot_load_oz', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('shot_load_g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_cartridge', 'shot_load_g')
    op.drop_column('firearm_cartridge', 'shot_load_oz')
    # ### end Alembic commands ###
