"""add archery_round.magnification

Revision ID: 94e0177a98ad
Revises: 3f8cd53ea2c3
Create Date: 2025-03-22 22:03:41.751934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e0177a98ad'
down_revision: Union[str, None] = '3f8cd53ea2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_round', sa.Column('magnification', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archery_round', 'magnification')
    # ### end Alembic commands ###
