"""renaming shotgun-related cartridge columns

Revision ID: 971f46e729ec
Revises: 98cc5f273cef
Create Date: 2025-11-22 16:30:26.889217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971f46e729ec'
down_revision: Union[str, None] = '98cc5f273cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firearm_cartridge', 'buckshot_type', new_column_name='shot_size')
    op.add_column('firearm_cartridge', sa.Column('shot_material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_cartridge', 'shot_material')
    op.alter_column('firearm_cartridge', 'shot_size', new_column_name='buckshot_type')
    # ### end Alembic commands ###
