"""add shotgun_choke.type

Revision ID: 98cc5f273cef
Revises: ead0a6805167
Create Date: 2025-11-15 17:07:23.721408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cc5f273cef'
down_revision: Union[str, None] = 'ead0a6805167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotgun_choke', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shotgun_choke', 'type')
    # ### end Alembic commands ###
