"""remove model.barrel_type

Revision ID: 98f4649a2473
Revises: 971f46e729ec
Create Date: 2025-11-22 17:09:25.152063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f4649a2473'
down_revision: Union[str, None] = '971f46e729ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_model', 'barrel_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_model', sa.Column('barrel_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
