"""trap target presentation

Revision ID: 9bf2d8a131e5
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 19:07:24.899974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf2d8a131e5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trap_target_presentation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_presentation', sa.String(), nullable=True),
    sa.Column('num_targets', sa.Integer(), nullable=True),
    sa.Column('doubles_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trap_round', sa.Column('trap_target_presentation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trap_round_trap_target_presentation_id'), 'trap_round', ['trap_target_presentation_id'], unique=False)
    op.create_foreign_key(None, 'trap_round', 'trap_target_presentation', ['trap_target_presentation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trap_round', type_='foreignkey')
    op.drop_index(op.f('ix_trap_round_trap_target_presentation_id'), table_name='trap_round')
    op.drop_column('trap_round', 'trap_target_presentation_id')
    op.drop_table('trap_target_presentation')
    # ### end Alembic commands ###
