"""firearm_ammunition

Revision ID: 9e72b9aad179
Revises: 278ca4453b3c
Create Date: 2024-12-14 18:00:15.501881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e72b9aad179'
down_revision: Union[str, None] = '278ca4453b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firearm_ammunition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_cartridge_id', sa.Integer(), nullable=True),
    sa.Column('firearm_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('casing', sa.String(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firearm_cartridge_id'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['firearm_manufacturer_id'], ['firearm_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firearm_ammunition')
    # ### end Alembic commands ###
