"""add archery_sight

Revision ID: a26f5d68f9c7
Revises: 7d290d282b91
Create Date: 2025-03-08 23:35:00.040207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a26f5d68f9c7'
down_revision: Union[str, None] = '7d290d282b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archery_sight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archery_sight')
    # ### end Alembic commands ###
