"""refine firearm_cartridge

Revision ID: a5930e0bfbae
Revises: ec0b7672b800
Create Date: 2024-12-14 18:41:47.153558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5930e0bfbae'
down_revision: Union[str, None] = 'ec0b7672b800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('length_in', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('length_mm', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('buckshot_type', sa.String(), nullable=True))
    op.drop_column('firearm_cartridge', 'casing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('casing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('firearm_cartridge', 'buckshot_type')
    op.drop_column('firearm_cartridge', 'length_mm')
    op.drop_column('firearm_cartridge', 'length_in')
    # ### end Alembic commands ###
