"""new tables for books

Revision ID: aacf8ea7e41c
Revises: ff48880b075d
Create Date: 2025-08-23 17:40:33.784827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aacf8ea7e41c'
down_revision: Union[str, None] = 'ff48880b075d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_format',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book_publisher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_books', sa.Integer(), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_translator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('isbn13', sa.String(length=15), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('date_read', sa.Date(), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), nullable=True),
    sa.Column('series_order', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['book_format.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['book_publisher.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['book_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('isbn13')
    )
    op.create_table('book_to_book_author',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_author_id'], ['book_author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'book_author_id')
    )
    op.create_table('book_to_book_language',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['book_language_id'], ['book_language.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'book_language_id')
    )
    op.create_table('book_to_book_translator',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_translator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['book_translator_id'], ['book_translator.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'book_translator_id')
    )
    op.drop_index('ix_library_author_id', table_name='library')
    op.drop_index('ix_library_composition_language_id', table_name='library')
    op.drop_index('ix_library_language1_id', table_name='library')
    op.drop_table('library')
    op.drop_table('binding')
    op.drop_table('language')
    op.drop_table('publisher')
    op.drop_table('author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='publisher_pkey')
    )
    op.create_table('language',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='language_pkey')
    )
    op.create_table('binding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='binding_pkey')
    )
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('author_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='author_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_main', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title_secondary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_volume', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('volume_in_series', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_published', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('year_published_original', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('year_read', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('month_read', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('day_read', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_additional_id', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('composition_language_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language3_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('translator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('translator_additional_id', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('binding_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='library_author_id_fkey'),
    sa.ForeignKeyConstraint(['binding_id'], ['binding.id'], name='library_binding_id_fkey'),
    sa.ForeignKeyConstraint(['composition_language_id'], ['language.id'], name='library_composition_language_id_fkey'),
    sa.ForeignKeyConstraint(['language1_id'], ['language.id'], name='library_language1_id_fkey'),
    sa.ForeignKeyConstraint(['language1_id'], ['language.id'], name='library_language1_id_fkey1'),
    sa.ForeignKeyConstraint(['language2_id'], ['language.id'], name='library_language2_id_fkey'),
    sa.ForeignKeyConstraint(['language3_id'], ['language.id'], name='library_language3_id_fkey'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name='library_publisher_id_fkey'),
    sa.ForeignKeyConstraint(['translator_id'], ['author.id'], name='library_translator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='library_pkey')
    )
    op.create_index('ix_library_language1_id', 'library', ['language1_id'], unique=False)
    op.create_index('ix_library_composition_language_id', 'library', ['composition_language_id'], unique=False)
    op.create_index('ix_library_author_id', 'library', ['author_id'], unique=False)
    op.drop_table('book_to_book_translator')
    op.drop_table('book_to_book_language')
    op.drop_table('book_to_book_author')
    op.drop_table('book')
    op.drop_table('book_translator')
    op.drop_table('book_series')
    op.drop_table('book_publisher')
    op.drop_table('book_language')
    op.drop_table('book_format')
    op.drop_table('book_author')
    # ### end Alembic commands ###
