"""change spine column name

Revision ID: b602776aa9c4
Revises: 35782ed4788a
Create Date: 2025-05-17 14:10:57.382531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b602776aa9c4'
down_revision: Union[str, None] = '35782ed4788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_arrow', sa.Column('spine', sa.Integer(), nullable=True))
    op.drop_column('archery_arrow', 'spine_grain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archery_arrow', sa.Column('spine_grain', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('archery_arrow', 'spine')
    # ### end Alembic commands ###
