"""add new columsn to firearm_cartridge

Revision ID: b90dd1c8cabc
Revises: 7cd2d452f6ca
Create Date: 2024-12-21 23:10:35.082973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b90dd1c8cabc'
down_revision: Union[str, None] = '7cd2d452f6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('length_in_case', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('length_mm_case', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_in_case', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_mm_case', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_in_bullet', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_mm_bullet', sa.Float(), nullable=True))
    op.drop_column('firearm_cartridge', 'length_mm')
    op.drop_column('firearm_cartridge', 'length_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('length_in', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('firearm_cartridge', sa.Column('length_mm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('firearm_cartridge', 'diameter_mm_bullet')
    op.drop_column('firearm_cartridge', 'diameter_in_bullet')
    op.drop_column('firearm_cartridge', 'diameter_mm_case')
    op.drop_column('firearm_cartridge', 'diameter_in_case')
    op.drop_column('firearm_cartridge', 'length_mm_case')
    op.drop_column('firearm_cartridge', 'length_in_case')
    # ### end Alembic commands ###
