"""add firearm architecture

Revision ID: bd91c2bd3b24
Revises: c80bab5039fc
Create Date: 2024-10-19 22:16:32.292464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd91c2bd3b24'
down_revision: Union[str, None] = 'c80bab5039fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firearm_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_cartridge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('strike_type', sa.String(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_dealer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_province', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_manufacturer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_province', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_range',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_province', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_restriction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restriction_type', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('full_size_cm', sa.Float(), nullable=True),
    sa.Column('actual_size_cm', sa.Float(), nullable=True),
    sa.Column('cm_x', sa.Float(), nullable=True),
    sa.Column('cm_ten', sa.Float(), nullable=True),
    sa.Column('cm_nine', sa.Float(), nullable=True),
    sa.Column('cm_eight', sa.Float(), nullable=True),
    sa.Column('cm_seven', sa.Float(), nullable=True),
    sa.Column('cm_six', sa.Float(), nullable=True),
    sa.Column('cm_five', sa.Float(), nullable=True),
    sa.Column('cm_four', sa.Float(), nullable=True),
    sa.Column('cm_three', sa.Float(), nullable=True),
    sa.Column('cm_two', sa.Float(), nullable=True),
    sa.Column('cm_one', sa.Float(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firearm_action_id', sa.Integer(), nullable=False),
    sa.Column('barrel_type', sa.String(), nullable=True),
    sa.Column('barrel_length_in', sa.Float(), nullable=True),
    sa.Column('barrel_length_cm', sa.Float(), nullable=True),
    sa.Column('country_iso_origin', sa.String(length=2), nullable=True),
    sa.Column('weight_lb', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('rear_sight', sa.Boolean(), nullable=True),
    sa.Column('front_sight', sa.Boolean(), nullable=True),
    sa.Column('firearm_restriction_id', sa.Integer(), nullable=False),
    sa.Column('cartridge_id1', sa.Integer(), nullable=False),
    sa.Column('capacity1', sa.Integer(), nullable=True),
    sa.Column('cartridge_id2', sa.Integer(), nullable=True),
    sa.Column('capacity2', sa.Integer(), nullable=True),
    sa.Column('cartridge_id3', sa.Integer(), nullable=True),
    sa.Column('capacity3', sa.Integer(), nullable=True),
    sa.Column('cartridge_id4', sa.Integer(), nullable=True),
    sa.Column('capacity4', sa.Integer(), nullable=True),
    sa.Column('cartridge_id5', sa.Integer(), nullable=True),
    sa.Column('capacity5', sa.Integer(), nullable=True),
    sa.Column('cartridge_id6', sa.Integer(), nullable=True),
    sa.Column('capacity6', sa.Integer(), nullable=True),
    sa.Column('cartridge_id7', sa.Integer(), nullable=True),
    sa.Column('capacity7', sa.Integer(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_id1'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id2'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id3'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id4'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id5'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id6'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['cartridge_id7'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['firearm_action_id'], ['firearm_action.id'], ),
    sa.ForeignKeyConstraint(['firearm_manufacturer_id'], ['firearm_manufacturer.id'], ),
    sa.ForeignKeyConstraint(['firearm_restriction_id'], ['firearm_restriction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_visit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_range_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.String(length=4), nullable=True),
    sa.Column('time_end', sa.String(length=4), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firearm_range_id'], ['firearm_range.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firearm_end',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_visit_id', sa.Integer(), nullable=False),
    sa.Column('firearm_model_id', sa.Integer(), nullable=True),
    sa.Column('firearm_cartridge_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('firearm_target_id', sa.Integer(), nullable=True),
    sa.Column('shots_scored', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firearm_cartridge_id'], ['firearm_cartridge.id'], ),
    sa.ForeignKeyConstraint(['firearm_model_id'], ['firearm_model.id'], ),
    sa.ForeignKeyConstraint(['firearm_target_id'], ['firearm_target.id'], ),
    sa.ForeignKeyConstraint(['firearm_visit_id'], ['firearm_visit.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firearm_end_firearm_visit_id'), 'firearm_end', ['firearm_visit_id'], unique=False)
    op.create_table('firearm_trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('firearm_model_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('firearm_dealer_id', sa.Integer(), nullable=False),
    sa.Column('buy_sell', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firearm_dealer_id'], ['firearm_dealer.id'], ),
    sa.ForeignKeyConstraint(['firearm_model_id'], ['firearm_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firearm_trade_trade_date'), 'firearm_trade', ['trade_date'], unique=False)
    op.create_table('firearm_shot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_end_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_x', sa.Boolean(), nullable=True),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firearm_end_id'], ['firearm_end.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firearm_shot_firearm_end_id'), 'firearm_shot', ['firearm_end_id'], unique=False)
    op.alter_column('archery_round', 'start_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.alter_column('archery_round', 'end_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archery_round', 'end_time',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('archery_round', 'start_time',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_firearm_shot_firearm_end_id'), table_name='firearm_shot')
    op.drop_table('firearm_shot')
    op.drop_index(op.f('ix_firearm_trade_trade_date'), table_name='firearm_trade')
    op.drop_table('firearm_trade')
    op.drop_index(op.f('ix_firearm_end_firearm_visit_id'), table_name='firearm_end')
    op.drop_table('firearm_end')
    op.drop_table('firearm_visit')
    op.drop_table('firearm_model')
    op.drop_table('firearm_target')
    op.drop_table('firearm_restriction')
    op.drop_table('firearm_range')
    op.drop_table('firearm_manufacturer')
    op.drop_table('firearm_dealer')
    op.drop_table('firearm_cartridge')
    op.drop_table('firearm_action')
    # ### end Alembic commands ###
