"""correc typo in relationship

Revision ID: be4279d86e51
Revises: 
Create Date: 2023-11-10 22:43:25.154235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4279d86e51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_date', sa.Date(), nullable=False),
    sa.Column('bow_weight_lb', sa.Integer(), nullable=False),
    sa.Column('bow_length_in', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('num_x', sa.Integer(), nullable=False),
    sa.Column('num_10', sa.Integer(), nullable=False),
    sa.Column('num_9', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('mental_status', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Boolean(), nullable=True),
    sa.Column('days_since_last_practice', sa.Integer(), nullable=True),
    sa.Column('stdev_ends', sa.Float(), nullable=False),
    sa.Column('stdev_shots', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_bow_weight_lb'), 'rounds', ['bow_weight_lb'], unique=False)
    op.create_index(op.f('ix_rounds_location'), 'rounds', ['location'], unique=False)
    op.create_index(op.f('ix_rounds_total_score'), 'rounds', ['total_score'], unique=False)
    op.create_table('ends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rounds_id', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('shots_ordered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rounds_id'], ['rounds.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ends_rounds_id'), 'ends', ['rounds_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ends_id', sa.Integer(), nullable=False),
    sa.Column('shot', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_x', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ends_id'], ['ends.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('expense_transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expense_transactions', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expense_transactions', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expense_transactions', 'expense_source',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expense_transactions', 'expense_comment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expense_transactions', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('expense_transactions_transaction_date_category_idx', table_name='expense_transactions')
    op.drop_index('expense_transactions_transaction_date_idx', table_name='expense_transactions')
    op.create_index(op.f('ix_expense_transactions_transaction_date'), 'expense_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_transactions_transaction_date'), table_name='expense_transactions')
    op.create_index('expense_transactions_transaction_date_idx', 'expense_transactions', ['transaction_date'], unique=False)
    op.create_index('expense_transactions_transaction_date_category_idx', 'expense_transactions', ['transaction_date', 'category'], unique=False)
    op.alter_column('expense_transactions', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('expense_transactions', 'expense_comment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('expense_transactions', 'expense_source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('expense_transactions', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('expense_transactions', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expense_transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('shots')
    op.drop_index(op.f('ix_ends_rounds_id'), table_name='ends')
    op.drop_table('ends')
    op.drop_index(op.f('ix_rounds_total_score'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_location'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_bow_weight_lb'), table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###
