"""archery_release_aid

Revision ID: c4647653d993
Revises: e707d18da8d9
Create Date: 2025-09-14 19:23:58.238241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4647653d993'
down_revision: Union[str, None] = 'e707d18da8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archery_release_aid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('archery_round', sa.Column('archery_release_aid_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'archery_round', 'archery_release_aid', ['archery_release_aid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archery_round', type_='foreignkey')
    op.drop_column('archery_round', 'archery_release_aid_id')
    op.drop_table('archery_release_aid')
    # ### end Alembic commands ###
