"""add notes column to credentials

Revision ID: c47ac26f028b
Revises: 75ce863c48cd
Create Date: 2024-02-23 22:53:23.066427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47ac26f028b'
down_revision: Union[str, None] = '75ce863c48cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'notes')
    # ### end Alembic commands ###
