"""binding->binding_id

Revision ID: c56c3ea14765
Revises: 0c4f71795dea
Create Date: 2024-09-08 00:56:17.147273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56c3ea14765'
down_revision: Union[str, None] = '0c4f71795dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('binding_id', sa.SmallInteger(), nullable=True))
    op.drop_constraint('library_binding_fkey', 'library', type_='foreignkey')
    op.create_foreign_key('library_binding_id_fkey', 'library', 'binding', ['binding_id'], ['id'])
    op.drop_column('library', 'binding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('binding', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint('library_binding_id_fkey', 'library', type_='foreignkey')
    op.create_foreign_key('library_binding_fkey', 'library', 'binding', ['binding'], ['id'])
    op.drop_column('library', 'binding_id')
    # ### end Alembic commands ###
