"""overhaul archery architecture

Revision ID: c80bab5039fc
Revises: c56c3ea14765
Create Date: 2024-10-19 21:38:35.947186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c80bab5039fc'
down_revision: Union[str, None] = 'c56c3ea14765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archery_bow_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_manufacturer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_range',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_province', sa.String(), nullable=True),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('outdoor', sa.Boolean(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('full_size_cm', sa.Float(), nullable=True),
    sa.Column('actual_size_cm', sa.Float(), nullable=True),
    sa.Column('cm_x', sa.Float(), nullable=True),
    sa.Column('cm_ten', sa.Float(), nullable=True),
    sa.Column('cm_nine', sa.Float(), nullable=True),
    sa.Column('cm_eight', sa.Float(), nullable=True),
    sa.Column('cm_seven', sa.Float(), nullable=True),
    sa.Column('cm_six', sa.Float(), nullable=True),
    sa.Column('cm_five', sa.Float(), nullable=True),
    sa.Column('cm_four', sa.Float(), nullable=True),
    sa.Column('cm_three', sa.Float(), nullable=True),
    sa.Column('cm_two', sa.Float(), nullable=True),
    sa.Column('cm_one', sa.Float(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_arrow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fletching', sa.String(), nullable=True),
    sa.Column('size_mm', sa.Float(), nullable=True),
    sa.Column('spine_grain', sa.Integer(), nullable=True),
    sa.Column('shaft_length_in', sa.Float(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_limb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_length_in', sa.Float(), nullable=True),
    sa.Column('draw_weight_lb_min', sa.Float(), nullable=True),
    sa.Column('draw_weight_lb_max', sa.Float(), nullable=True),
    sa.Column('archery_bow_type_id', sa.Integer(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_bow_type_id'], ['archery_bow_type.id'], ),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_riser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_in', sa.Float(), nullable=True),
    sa.Column('rh_lh', sa.String(length=2), nullable=True),
    sa.Column('archery_bow_type_id', sa.Integer(), nullable=True),
    sa.Column('letoff_pct', sa.Float(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_bow_type_id'], ['archery_bow_type.id'], ),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archery_round',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('archery_range_id', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('archery_target_id', sa.Integer(), nullable=True),
    sa.Column('sight', sa.Boolean(), nullable=False),
    sa.Column('clicker', sa.Boolean(), nullable=False),
    sa.Column('stablisation', sa.Boolean(), nullable=False),
    sa.Column('archery_riser_id', sa.Integer(), nullable=True),
    sa.Column('archery_limb_id', sa.Integer(), nullable=True),
    sa.Column('draw_weight_lb', sa.Float(), nullable=True),
    sa.Column('archery_arrow_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('num_x', sa.Integer(), nullable=False),
    sa.Column('num_10', sa.Integer(), nullable=False),
    sa.Column('num_9', sa.Integer(), nullable=False),
    sa.Column('stdev_ends', sa.Float(), nullable=False),
    sa.Column('stdev_shots', sa.Float(), nullable=False),
    sa.Column('num_ends', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('condition_mental', sa.Integer(), nullable=True),
    sa.Column('condition_env', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Boolean(), nullable=True),
    sa.Column('days_since_last_practice', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_arrow_id'], ['archery_arrow.id'], ),
    sa.ForeignKeyConstraint(['archery_limb_id'], ['archery_limb.id'], ),
    sa.ForeignKeyConstraint(['archery_range_id'], ['archery_range.id'], ),
    sa.ForeignKeyConstraint(['archery_riser_id'], ['archery_riser.id'], ),
    sa.ForeignKeyConstraint(['archery_target_id'], ['archery_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archery_round_date'), 'archery_round', ['date'], unique=False)
    op.create_table('archery_end',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_round_id', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('num_shots', sa.Integer(), nullable=False),
    sa.Column('shots_ordered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['archery_round_id'], ['archery_round.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archery_end_archery_round_id'), 'archery_end', ['archery_round_id'], unique=False)
    op.create_table('archery_shot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_end_id', sa.Integer(), nullable=False),
    sa.Column('shot', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_x', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['archery_end_id'], ['archery_end.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shots')
    op.drop_index('ix_ends_rounds_id', table_name='ends')
    op.drop_table('ends')
    op.drop_index('ix_rounds_bow', table_name='rounds')
    op.drop_index('ix_rounds_bow_weight_lb', table_name='rounds')
    op.drop_index('ix_rounds_distance_m', table_name='rounds')
    op.drop_index('ix_rounds_location', table_name='rounds')
    op.drop_index('ix_rounds_round_date', table_name='rounds')
    op.drop_index('ix_rounds_total_score', table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ends_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_x', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ends_id'], ['ends.id'], name='shots_ends_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shots_pkey')
    )
    op.create_table('rounds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('rounds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('round_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('distance_m', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_size_cm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sight', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('clicker', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('stabliser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bow', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arrow_stiffness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bow_weight_lb', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bow_length_in', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_10', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_9', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_shots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mental_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conditions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hunger', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('days_since_last_practice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stdev_ends', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stdev_shots', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rounds_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_rounds_total_score', 'rounds', ['total_score'], unique=False)
    op.create_index('ix_rounds_round_date', 'rounds', ['round_date'], unique=False)
    op.create_index('ix_rounds_location', 'rounds', ['location'], unique=False)
    op.create_index('ix_rounds_distance_m', 'rounds', ['distance_m'], unique=False)
    op.create_index('ix_rounds_bow_weight_lb', 'rounds', ['bow_weight_lb'], unique=False)
    op.create_index('ix_rounds_bow', 'rounds', ['bow'], unique=False)
    op.create_table('ends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rounds_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_shots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_ordered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rounds_id'], ['rounds.id'], name='ends_rounds_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ends_pkey')
    )
    op.create_index('ix_ends_rounds_id', 'ends', ['rounds_id'], unique=False)
    op.drop_table('archery_shot')
    op.drop_index(op.f('ix_archery_end_archery_round_id'), table_name='archery_end')
    op.drop_table('archery_end')
    op.drop_index(op.f('ix_archery_round_date'), table_name='archery_round')
    op.drop_table('archery_round')
    op.drop_table('archery_riser')
    op.drop_table('archery_limb')
    op.drop_table('archery_arrow')
    op.drop_table('archery_target')
    op.drop_table('archery_range')
    op.drop_table('archery_manufacturer')
    op.drop_table('archery_bow_type')
    # ### end Alembic commands ###
