"""remove book.publication_date

Revision ID: cb3f76b0dfb9
Revises: d16ed48126e4
Create Date: 2025-08-23 20:18:21.753069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3f76b0dfb9'
down_revision: Union[str, None] = 'd16ed48126e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
