"""break up publication_date

Revision ID: d16ed48126e4
Revises: 6e8dc356df8b
Create Date: 2025-08-23 20:07:57.462952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16ed48126e4'
down_revision: Union[str, None] = '6e8dc356df8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_year', sa.SmallInteger(), nullable=True))
    op.add_column('book', sa.Column('publication_month', sa.SmallInteger(), nullable=True))
    op.add_column('book', sa.Column('publication_day', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_day')
    op.drop_column('book', 'publication_month')
    op.drop_column('book', 'publication_year')
    # ### end Alembic commands ###
