"""add library and binding

Revision ID: d4499df43755
Revises: 9077020939f5
Create Date: 2024-09-07 22:54:07.962298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4499df43755'
down_revision: Union[str, None] = '9077020939f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_main', sa.String(), nullable=True),
    sa.Column('title_secondary', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_last_name', sa.String(), nullable=True),
    sa.Column('author_first_name', sa.String(), nullable=True),
    sa.Column('author_additional', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_composition', sa.String(), nullable=True),
    sa.Column('language1', sa.String(), nullable=True),
    sa.Column('language2', sa.String(), nullable=True),
    sa.Column('language3', sa.String(), nullable=True),
    sa.Column('translator', sa.String(), nullable=True),
    sa.Column('translator_additional', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('num_volume', sa.SmallInteger(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('volume_in_series', sa.SmallInteger(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('binding', sa.SmallInteger(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('year_published', sa.SmallInteger(), nullable=True),
    sa.Column('year_published_original', sa.SmallInteger(), nullable=True),
    sa.Column('year_read', sa.SmallInteger(), nullable=True),
    sa.Column('month_read', sa.SmallInteger(), nullable=True),
    sa.Column('day_read', sa.SmallInteger(), nullable=True),
    sa.Column('datetime_entered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['binding'], ['binding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_binding'), 'library', ['binding'], unique=False)
    op.create_index(op.f('ix_library_language1'), 'library', ['language1'], unique=False)
    op.create_index(op.f('ix_library_language_composition'), 'library', ['language_composition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_language_composition'), table_name='library')
    op.drop_index(op.f('ix_library_language1'), table_name='library')
    op.drop_index(op.f('ix_library_binding'), table_name='library')
    op.drop_table('library')
    op.drop_table('binding')
    # ### end Alembic commands ###
