"""add firearm_cartridge.casing

Revision ID: d499baa2a116
Revises: 67ab9433f6c7
Create Date: 2024-11-02 15:11:39.645838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499baa2a116'
down_revision: Union[str, None] = '67ab9433f6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('casing', sa.String(), nullable=True))
    op.create_foreign_key(None, 'library', 'language', ['language1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_column('firearm_cartridge', 'casing')
    # ### end Alembic commands ###
