"""add firearm_end.supporting_hands

Revision ID: d72fd54b6da7
Revises: dff749a0c8bd
Create Date: 2024-12-28 20:29:20.811123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72fd54b6da7'
down_revision: Union[str, None] = 'dff749a0c8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('supporting_hands', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_end', 'supporting_hands')
    # ### end Alembic commands ###
