"""make some archery columns nullable

Revision ID: dbe07ac1ae47
Revises: 9337aac80759
Create Date: 2025-12-20 22:13:18.785397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe07ac1ae47'
down_revision: Union[str, None] = '9337aac80759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archery_round', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archery_round', 'num_x',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archery_round', 'num_10',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archery_round', 'num_9',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archery_round', 'num_ends',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archery_round', 'num_shots',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archery_round', 'num_shots',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archery_round', 'num_ends',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archery_round', 'num_9',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archery_round', 'num_10',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archery_round', 'num_x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archery_round', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
