"""new firearm_cartridge columns

Revision ID: dff749a0c8bd
Revises: b90dd1c8cabc
Create Date: 2024-12-22 00:33:11.494723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff749a0c8bd'
down_revision: Union[str, None] = 'b90dd1c8cabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('diameter_in_base', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_mm_base', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_in_land', sa.Float(), nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_mm_land', sa.Float(), nullable=True))
    op.drop_column('firearm_cartridge', 'diameter_mm_case')
    op.drop_column('firearm_cartridge', 'diameter_in_case')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_cartridge', sa.Column('diameter_in_case', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('firearm_cartridge', sa.Column('diameter_mm_case', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('firearm_cartridge', 'diameter_mm_land')
    op.drop_column('firearm_cartridge', 'diameter_in_land')
    op.drop_column('firearm_cartridge', 'diameter_mm_base')
    op.drop_column('firearm_cartridge', 'diameter_in_base')
    # ### end Alembic commands ###
