"""remove book_author birth_date and death_date

Revision ID: e707d18da8d9
Revises: 04e051f36fca
Create Date: 2025-08-24 12:48:11.715316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e707d18da8d9'
down_revision: Union[str, None] = '04e051f36fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_author', 'birth_date')
    op.drop_column('book_author', 'death_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_author', sa.Column('death_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('book_author', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
