"""remove isbn uniqueness

Revision ID: e91ff566a273
Revises: 6894690d7d91
Create Date: 2025-08-24 12:04:14.621976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91ff566a273'
down_revision: Union[str, None] = '6894690d7d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_isbn13_key', 'book', type_='unique')
    op.drop_constraint('book_isbn_key', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('book_isbn_key', 'book', ['isbn'])
    op.create_unique_constraint('book_isbn13_key', 'book', ['isbn13'])
    # ### end Alembic commands ###
