"""trap scoring

Revision ID: ead0a6805167
Revises: c4647653d993
Create Date: 2025-11-15 17:01:20.317945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ead0a6805167'
down_revision: Union[str, None] = 'c4647653d993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shotgun_choke',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('constriction', sa.String(), nullable=True),
    sa.Column('diametre_in', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firearm_manufacturer_id'], ['firearm_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trap_round',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_end_id', sa.Integer(), nullable=False),
    sa.Column('distance_yard', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('num_break', sa.SmallInteger(), nullable=True),
    sa.Column('starting_station', sa.SmallInteger(), nullable=True),
    sa.Column('shotgun_choke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firearm_end_id'], ['firearm_end.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shotgun_choke_id'], ['shotgun_choke.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trap_round_firearm_end_id'), 'trap_round', ['firearm_end_id'], unique=False)
    op.create_index(op.f('ix_trap_round_shotgun_choke_id'), 'trap_round', ['shotgun_choke_id'], unique=False)
    op.create_table('trap_shot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trap_round_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('num_break', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['trap_round_id'], ['trap_round.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trap_shot_trap_round_id'), 'trap_shot', ['trap_round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trap_shot_trap_round_id'), table_name='trap_shot')
    op.drop_table('trap_shot')
    op.drop_index(op.f('ix_trap_round_shotgun_choke_id'), table_name='trap_round')
    op.drop_index(op.f('ix_trap_round_firearm_end_id'), table_name='trap_round')
    op.drop_table('trap_round')
    op.drop_table('shotgun_choke')
    # ### end Alembic commands ###
