"""add muzzle velocity and weight in grain

Revision ID: ec0b7672b800
Revises: fbc324789d0b
Create Date: 2024-12-14 18:12:49.237230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0b7672b800'
down_revision: Union[str, None] = 'fbc324789d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_ammunition', sa.Column('muzzle_velocity_fps', sa.Float(), nullable=True))
    op.add_column('firearm_ammunition', sa.Column('weight_grain', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_ammunition', 'weight_grain')
    op.drop_column('firearm_ammunition', 'muzzle_velocity_fps')
    # ### end Alembic commands ###
