"""remove trap target presentation

Revision ID: f4ab8e7d46f0
Revises: b7e4c9d21f0a
Create Date: 2026-07-01 15:23:02.683982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ab8e7d46f0'
down_revision: Union[str, None] = 'b7e4c9d21f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skeet_shot', 'bird')
    op.drop_index('ix_trap_round_trap_target_presentation_id', table_name='trap_round')
    op.drop_constraint('trap_round_trap_target_presentation_id_fkey', 'trap_round', type_='foreignkey')
    op.drop_column('trap_round', 'trap_target_presentation_id')
    op.drop_table('trap_target_presentation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trap_target_presentation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_presentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_targets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doubles_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trap_target_presentation_pkey')
    )
    op.add_column('trap_round', sa.Column('trap_target_presentation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trap_round_trap_target_presentation_id_fkey', 'trap_round', 'trap_target_presentation', ['trap_target_presentation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_trap_round_trap_target_presentation_id', 'trap_round', ['trap_target_presentation_id'], unique=False)
    op.add_column('skeet_shot', sa.Column('bird', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
