"""add stance column to firearm_end

Revision ID: f7dfa3d8f3e4
Revises: 2e346993059b
Create Date: 2024-12-01 17:42:57.199410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dfa3d8f3e4'
down_revision: Union[str, None] = '2e346993059b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('stance', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firearm_end', 'stance')
    # ### end Alembic commands ###
