"""add back firearm_end.firearm_cartridge_id

Revision ID: fbc324789d0b
Revises: 1b19233e7d43
Create Date: 2024-12-14 18:04:05.744769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc324789d0b'
down_revision: Union[str, None] = '1b19233e7d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearm_end', sa.Column('firearm_cartridge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'firearm_end', 'firearm_cartridge', ['firearm_cartridge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'firearm_end', type_='foreignkey')
    op.drop_column('firearm_end', 'firearm_cartridge_id')
    # ### end Alembic commands ###
