"""skeet tables

Revision ID: ff1d3dfb3a6b
Revises: 69f0e15470dc
Create Date: 2026-05-08 20:52:35.094953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1d3dfb3a6b'
down_revision: Union[str, None] = '69f0e15470dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skeet_round',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firearm_end_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('num_break', sa.SmallInteger(), nullable=True),
    sa.Column('shotgun_choke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firearm_end_id'], ['firearm_end.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shotgun_choke_id'], ['shotgun_choke.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skeet_round_firearm_end_id'), 'skeet_round', ['firearm_end_id'], unique=False)
    op.create_index(op.f('ix_skeet_round_shotgun_choke_id'), 'skeet_round', ['shotgun_choke_id'], unique=False)
    op.create_table('skeet_shot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skeet_round_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.SmallInteger(), nullable=False),
    sa.Column('is_doubles', sa.Boolean(), nullable=False),
    sa.Column('bird', sa.String(), nullable=True),
    sa.Column('num_break', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['skeet_round_id'], ['skeet_round.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skeet_shot_skeet_round_id'), 'skeet_shot', ['skeet_round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skeet_shot_skeet_round_id'), table_name='skeet_shot')
    op.drop_table('skeet_shot')
    op.drop_index(op.f('ix_skeet_round_shotgun_choke_id'), table_name='skeet_round')
    op.drop_index(op.f('ix_skeet_round_firearm_end_id'), table_name='skeet_round')
    op.drop_table('skeet_round')
    # ### end Alembic commands ###
