"""add archery_arrow_rest

Revision ID: ff48880b075d
Revises: 2f6ba5f423d2
Create Date: 2025-05-31 00:34:44.946109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff48880b075d'
down_revision: Union[str, None] = '2f6ba5f423d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archery_arrow_rest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archery_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('arrow_rest_type', sa.String(), nullable=True),
    sa.Column('datetime_entered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archery_manufacturer_id'], ['archery_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('archery_round', sa.Column('archery_arrow_rest_id', sa.Integer(), nullable=True))
    op.add_column('archery_round', sa.Column('variable_distance', sa.Boolean(), nullable=True))
    op.add_column('archery_round', sa.Column('known_distance', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'archery_round', 'archery_arrow_rest', ['archery_arrow_rest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archery_round', type_='foreignkey')
    op.drop_column('archery_round', 'known_distance')
    op.drop_column('archery_round', 'variable_distance')
    op.drop_column('archery_round', 'archery_arrow_rest_id')
    op.drop_table('archery_arrow_rest')
    # ### end Alembic commands ###
